# Generated by Django 5.2.8 on 2025-11-22 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='USSDLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Telecom provider session ID', max_length=100)),
                ('phone_number', models.CharField(help_text="Parent's phone number", max_length=20)),
                ('user_input', models.CharField(blank=True, help_text="User's menu selection", max_length=255)),
                ('menu_state', models.CharField(help_text='Current menu state', max_length=50)),
                ('response_sent', models.TextField(help_text='USSD response sent to user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'USSD Log',
                'verbose_name_plural': 'USSD Logs',
                'db_table': 'ussd_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redemption_type', models.CharField(choices=[('data', 'Mobile Data'), ('talktime', 'Talk Time'), ('sms', 'SMS Package'), ('reward', 'Physical Reward')], help_text='Type of redemption', max_length=20)),
                ('item_name', models.CharField(help_text='Name of the item being redeemed', max_length=100)),
                ('points_required', models.IntegerField(help_text='Porapoints required for redemption')),
                ('description', models.TextField(blank=True, help_text='Additional redemption details')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('redeemed', 'Redeemed')], default='pending', help_text='Current approval status', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_via_ussd', models.BooleanField(default=False, help_text='Whether approved through USSD')),
                ('ussd_session_id', models.CharField(blank=True, help_text='USSD session used for approval', max_length=100)),
                ('child', models.ForeignKey(help_text='Child requesting redemption', on_delete=django.db.models.deletion.CASCADE, related_name='redemption_requests', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(help_text='Parent for approval', on_delete=django.db.models.deletion.CASCADE, related_name='child_redemption_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Redemption Request',
                'verbose_name_plural': 'Redemption Requests',
                'db_table': 'redemption_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Telecom provider session ID', max_length=100, unique=True)),
                ('phone_number', models.CharField(help_text="Parent's phone number", max_length=20)),
                ('current_state', models.CharField(default='main_menu', help_text='Current menu state', max_length=50)),
                ('session_data', models.JSONField(default=dict, help_text='Session-specific data storage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Associated parent user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'USSD Session',
                'verbose_name_plural': 'USSD Sessions',
                'db_table': 'ussd_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenTimeSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('limit_type', models.CharField(choices=[('daily', 'Daily Limit'), ('weekly', 'Weekly Limit'), ('session', 'Per Session Limit')], default='daily', help_text='Type of time limit', max_length=20)),
                ('limit_minutes', models.IntegerField(help_text='Time limit in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the limit is currently active')),
                ('set_via_ussd', models.BooleanField(default=False, help_text='Whether set through USSD')),
                ('ussd_session_id', models.CharField(blank=True, help_text='USSD session used for setting', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(help_text='Child user', on_delete=django.db.models.deletion.CASCADE, related_name='screen_time_settings', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(help_text='Parent setting the limit', on_delete=django.db.models.deletion.CASCADE, related_name='child_screen_time_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Screen Time Setting',
                'verbose_name_plural': 'Screen Time Settings',
                'db_table': 'screen_time_settings',
                'ordering': ['-updated_at'],
                'unique_together': {('child', 'limit_type', 'is_active')},
            },
        ),
    ]
