# Generated by Django 4.2.7 on 2025-11-22 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_bn', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('description_bn', models.TextField()),
                ('achievement_type', models.CharField(choices=[('lesson_streak', 'Lesson Streak'), ('subject_mastery', 'Subject Mastery'), ('quiz_perfectionist', 'Quiz Perfect Score'), ('early_bird', 'Early Learner'), ('weekend_warrior', 'Weekend Learning'), ('speedster', 'Fast Learner'), ('persistent', 'Never Give Up'), ('explorer', 'Subject Explorer')], max_length=20)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('badge_color', models.CharField(default='#FFD700', max_length=7)),
                ('requirements', models.JSONField(default=dict)),
                ('reward_points', models.IntegerField(default=50)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='RewardCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_bn', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reward_type', models.CharField(choices=[('data_bundle', 'Internet Data Bundle'), ('talktime', 'Mobile Talktime'), ('sms_bundle', 'SMS Bundle'), ('digital_content', 'Digital Content'), ('physical_reward', 'Physical Reward')], max_length=20)),
                ('cost_points', models.IntegerField()),
                ('value_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_unit', models.CharField(max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('daily_limit_per_user', models.IntegerField(blank=True, null=True)),
                ('applink_product_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Reward Catalog',
                'db_table': 'reward_catalog',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.FloatField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.achievement')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Achievement',
                'verbose_name_plural': 'User Achievements',
                'db_table': 'user_achievements',
                'indexes': [models.Index(fields=['child', 'is_completed'], name='user_achiev_child_i_0fdd21_idx'), models.Index(fields=['completed_at'], name='user_achiev_complet_8c78fa_idx')],
                'unique_together': {('child', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('total_points_cost', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('delivery_phone', models.CharField(max_length=15)),
                ('delivery_details', models.JSONField(default=dict)),
                ('applink_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('applink_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.rewardcatalog')),
            ],
            options={
                'verbose_name': 'Reward Redemption',
                'verbose_name_plural': 'Reward Redemptions',
                'db_table': 'reward_redemptions',
                'indexes': [models.Index(fields=['child', 'status'], name='reward_rede_child_i_a807e0_idx'), models.Index(fields=['created_at'], name='reward_rede_created_4fc6eb_idx'), models.Index(fields=['applink_transaction_id'], name='reward_rede_applink_250dbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PorapointLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_amount', models.IntegerField(help_text='Amount of points changed (positive for earning, negative for spending)')),
                ('reason', models.CharField(choices=[('lesson_complete', 'Lesson Completion'), ('redemption', 'Points Redemption'), ('quiz_score', 'Quiz Performance'), ('daily_login', 'Daily Login'), ('streak_bonus', 'Streak Bonus'), ('achievement', 'Achievement Unlock'), ('referral', 'Referral Bonus'), ('manual_adjustment', 'Manual Adjustment'), ('data_purchase', 'Data Purchase'), ('talktime_purchase', 'Talktime Purchase'), ('refund', 'Refund'), ('penalty', 'Penalty'), ('expired', 'Points Expired')], help_text='Reason for the point change', max_length=30)),
                ('idempotency_key', models.CharField(help_text='Unique key to prevent duplicate transactions', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the transaction was created')),
                ('balance_after', models.IntegerField(help_text='Running balance after this transaction')),
                ('reference_id', models.CharField(blank=True, help_text='Reference to related object (lesson_id, achievement_id, etc.)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional transaction details')),
                ('metadata', models.JSONField(default=dict, help_text='Additional context data for the transaction')),
                ('applink_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('applink_status', models.CharField(default='pending', max_length=20)),
                ('child', models.ForeignKey(help_text='Child account for this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='porapoint_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Porapoint Transaction',
                'verbose_name_plural': 'Porapoint Transactions',
                'db_table': 'porapoint_ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['child', 'reason'], name='porapoint_l_child_i_83afdc_idx'), models.Index(fields=['created_at'], name='porapoint_l_created_cfce94_idx'), models.Index(fields=['applink_transaction_id'], name='porapoint_l_applink_a9e414_idx')],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leaderboard_type', models.CharField(choices=[('global_points', 'Global Points'), ('weekly_points', 'Weekly Points'), ('grade_points', 'Grade-wise Points'), ('subject_mastery', 'Subject Mastery'), ('streak_champion', 'Streak Champion')], max_length=20)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=10)),
                ('rank', models.IntegerField()),
                ('score', models.IntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'db_table': 'leaderboards',
                'indexes': [models.Index(fields=['leaderboard_type', 'period', 'rank'], name='leaderboard_leaderb_1597a6_idx'), models.Index(fields=['period_start', 'period_end'], name='leaderboard_period__ea532e_idx')],
                'unique_together': {('child', 'leaderboard_type', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField()),
                ('weekly_goals_met', models.IntegerField(default=0)),
                ('monthly_goals_met', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Streak',
                'verbose_name_plural': 'Daily Streaks',
                'db_table': 'daily_streaks',
                'unique_together': {('child',)},
            },
        ),
    ]
