# Generated by Django 4.2.7 on 2025-11-20 20:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('chapter_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('title_bn', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('learning_objectives', models.JSONField(default=list)),
                ('estimated_duration_minutes', models.IntegerField(default=30)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'db_table': 'chapters',
                'ordering': ['subject', 'grade', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('bangla', 'Bangla'), ('english', 'English'), ('math', 'Mathematics'), ('science', 'Science'), ('social_science', 'Social Science'), ('islam', 'Islam & Moral Education'), ('ict', 'ICT')], help_text='Subject for this lesson', max_length=20)),
                ('grade', models.IntegerField(help_text='Grade level (1-10) for this lesson')),
                ('title', models.CharField(help_text='Lesson title', max_length=200)),
                ('content_json', models.JSONField(default=dict, help_text='NCTB-aligned lesson package data')),
                ('title_bn', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lesson_type', models.CharField(choices=[('video', 'Video Lesson'), ('interactive', 'Interactive Content'), ('quiz', 'Quiz'), ('reading', 'Reading Material'), ('exercise', 'Exercise')], default='interactive', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=15)),
                ('porapoints_reward', models.IntegerField(default=10)),
                ('order', models.IntegerField(default=0)),
                ('is_free', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('download_size_mb', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'db_table': 'lessons',
                'ordering': ['chapter', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0, help_text='Score achieved in the lesson (0-100)')),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent on lesson in minutes')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the lesson was completed', null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='not_started', max_length=15)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('porapoints_earned', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progress',
                'db_table': 'lesson_progress',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('score', models.FloatField(default=0)),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField(default=0)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'db_table': 'quiz_attempts',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_bn', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('color_code', models.CharField(default='#2196F3', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_text_bn', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('drag_drop', 'Drag and Drop'), ('matching', 'Matching')], max_length=15)),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.JSONField(default=dict)),
                ('explanation', models.TextField(blank=True)),
                ('explanation_bn', models.TextField(blank=True)),
                ('points', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'db_table': 'quiz_questions',
                'ordering': ['lesson', 'order'],
            },
        ),
    ]
