# Generated by Django 4.2.7 on 2025-11-20 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='child',
            field=models.ForeignKey(help_text='Child who is taking the lesson', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(help_text='Lesson being taken', on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.chapter'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='lessons.subject'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['child', 'lesson'], name='quiz_attemp_child_i_8b66d3_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['completed_at'], name='quiz_attemp_complet_f97b11_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['child', 'status'], name='lesson_prog_child_i_6e30d7_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'completion_percentage'], name='lesson_prog_lesson__5393ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('child', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'grade', 'chapter_number')},
        ),
    ]
